<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>05dc0327-69d6-4876-ab84-74e0b7f67ecc</UserSecretsId>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.17"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.17">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AuthSessionManager.Application\AuthSessionManager.Application.csproj"/>
        <ProjectReference Include="..\AuthSessionManager.Infrastructure\AuthSessionManager.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
